name: air
description: A new Flutter application.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  alan_voice: ^2.0.7
  audioplayers: ^0.17.4
  cupertino_icons: ^1.0.2
  google_fonts: ^1.1.1
  velocity_x: ^1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
